name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v2
      - run: npm run build
      - if: github.ref_name == 'master'
        run: |
          ./script/gh-release.sh
          ./script/gh-deploy.sh
